"""empty message

Revision ID: 679130d012fe
Revises: 480d890c2af8
Create Date: 2024-03-05 14:54:34.275816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679130d012fe'
down_revision = '480d890c2af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=100), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('captcha')
    # ### end Alembic commands ###
